#!/bin/sh
#
# careers node.js service
#
# chkconfig:   35 99 99
# description: careers node.js service

# Source function library.
. /etc/rc.d/init.d/functions

dir="/workspace/careers-test/"
exec="$dir/bin/careers"
prog="careers-test"
pidfile="/var/run/careers/$prog.pid"
output_logfile="/var/log/careers/$prog.log"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon --pidfile $pidfile --user apache \
        "python -c 'import os; import sys; open(\"$pidfile\", \"w\").write(str(os.getpid())); os.execv(\"$exec\", [\"$exec\"] + sys.argv[1:])' $NODE_OPTS >> $output_logfile 2>&1 &"
    echo
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    echo "Process stopped." >> $output_logfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $exec
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?

